#!/bin/sh
# Automatically login to pulchowk campus ethernet when enp4s0 connection (ethernet) is up (activated)
USER=####
PASSWORD=####
if ( [ "$2" = "up" ] || [ "$2" = "dhcp4-change" ] ) && [[ "$1" = "enp7s0f1" || "$1" = "wlp0s20f3" ]]; then 
	curl -d "mode=191&username=$USER&password=$PASSWORD" http://10.100.1.1:8090/login.xml 
fi
